version: '3.8'

services:
  nginx:
    build: .
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 bot:bot
    ports:
      - 5000:5000
    env_file:
      - ./.env
